# Generated by Django 4.2.11 on 2024-06-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_landline_alter_doctor_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='practice_licence_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='national_id_card_image',
            field=models.URLField(),
        ),
    ]
