# Generated by Django 4.2.11 on 2024-06-26 16:22

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_doctor_city_alter_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guardian',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[accounts.models.validate_iranian_phone]),
        ),
    ]
