# Generated by Django 4.2.11 on 2024-06-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_doctor_is_active_guardian_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
