# Generated by Django 4.2.11 on 2024-06-26 19:42

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_guardian_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelManagers(
            name='ihmsuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='guardian',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.guardian'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_picture',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[accounts.models.validate_iranian_national_id]),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_file',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.medicalfile'),
            preserve_default=False,
        ),
    ]
