# Generated by Django 4.2.11 on 2024-06-27 12:11

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_medicalfile_alter_ihmsuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ihmsuser',
            name='birthdate',
            field=models.DateField(validators=[accounts.models.validate_adult_age]),
        ),
    ]
